import { useState } from 'react';
import type { FormEvent } from 'react';
import type { GuildPrivacy, GuildState } from '../utils/guildStore';
import { createGuild, getGuildState, leaveGuild } from '../utils/guildStore';
import { useEffect, useRef } from 'react';
import { addMessage, getMessages, reactToMessage, type ChatMessage } from '../utils/chatStore';
import { MemeSticker } from './MemeSticker';
import { isGuildApiConfigured, searchGuilds, type GuildSearchResult } from '../utils/guildApi';

type GuildTab = 'OVERVIEW' | 'MEMBERS' | 'CHAT' | 'RANKING' | 'ACTIVITY' | 'EVENTS' | 'MANAGEMENT';
const tabs: Array<[GuildTab, string]> = [['OVERVIEW', '⌂'], ['MEMBERS', '♙'], ['CHAT', '◌'], ['RANKING', '♜'], ['ACTIVITY', 'ϟ'], ['EVENTS', '◇'], ['MANAGEMENT', '⚙']];

export function Guild({ username, onHome, onShop, onSettings }: { username: string; onHome: () => void; onShop: () => void; onSettings: () => void }) {
  const [state, setState] = useState<GuildState | null>(() => getGuildState());
  const [tab, setTab] = useState<GuildTab>('OVERVIEW');
  const [showCreate, setShowCreate] = useState(false);
  const [confirmLeave, setConfirmLeave] = useState(false);
  const [notice, setNotice] = useState('');
  const [showSearch, setShowSearch] = useState(false);
  function handleLeave() { leaveGuild(); setState(null); setTab('OVERVIEW'); }
  return <div className="guild-shell"><div className="guild-grid" aria-hidden="true" /><div className="guild-aura" aria-hidden="true" />
    <header className="guild-header"><button className="guild-home-link" onClick={onHome}>← HOME</button><div><span className="eyebrow">COMMUNITY HUB</span><h1>♜ GUILD <MemeSticker kind="W" size="micro" className="meme-heading-sticker" /></h1><p>{state ? 'Your shared base for the arena.' : 'Find your people. Build something together.'}</p></div><span className="guild-notification">♢ <b>0</b></span></header>
    {state && <GuildIdentity state={state} />}
    <div className="guild-layout"><aside className="guild-sidebar"><label className="guild-mobile-select">SECTION<select value={tab} onChange={(event) => setTab(event.target.value as GuildTab)}>{tabs.map(([name]) => <option key={name}>{name}</option>)}</select></label><nav>{tabs.map(([name, icon]) => <button key={name} className={tab === name ? 'active' : ''} onClick={() => setTab(name)}><span>{icon}</span>{name}</button>)}</nav></aside>
      <main className="guild-content">{!state ? <GuildEmptyState onCreate={() => setShowCreate(true)} onFind={() => setShowSearch(true)} /> : <GuildTabContent tab={tab} state={state} username={username} onLeave={() => setConfirmLeave(true)} onNotice={setNotice} />}</main>
    </div>
    <nav className="bottom-nav guild-nav">{[['⌂', 'HOME'], ['◇', 'SHOP'], ['♜', 'LEADERBOARD'], ['⚔', 'PLAY MODE'], ['♢', 'GUILD'], ['⚙', 'SETTING']].map(([icon, label], index) => <button key={label} className={index === 4 ? 'active' : ''} onClick={index === 0 ? onHome : index === 1 ? onShop : index === 5 ? onSettings : undefined}><span>{icon}</span><small>{label}</small></button>)}</nav>
    {showCreate && <CreateGuildModal username={username} onClose={() => setShowCreate(false)} onCreated={(next) => { setState(next); setShowCreate(false); setNotice('Guild created locally. Connect the Guild API before production use.'); }} />}
    {showSearch && <GuildSearchModal onClose={() => setShowSearch(false)} />}
    {confirmLeave && <div className="modal-backdrop"><div className="confirm-modal"><span className="modal-icon">!</span><h2>Leave Guild?</h2><p>You will lose access to Guild Chat and Guild features.</p><div><button onClick={() => setConfirmLeave(false)}>CANCEL</button><button className="danger-button" onClick={() => { setConfirmLeave(false); handleLeave(); }}>LEAVE</button></div></div></div>}
    {notice && <div className="guild-toast">✓ {notice}</div>}
  </div>;
}

function GuildIdentity({ state }: { state: GuildState }) { return <section className="guild-identity"><div className="guild-emblem">♜</div><div className="guild-name-block"><span className="eyebrow">LOCAL GUILD</span><h2>{state.guild.name} <small>[{state.guild.tag}]</small></h2><p>{state.guild.description || 'No Guild description yet.'}</p></div><div className="guild-stats"><Stat label="GUILD ID" value={state.guild.id.slice(0, 13)} /><Stat label="MEMBERS" value={`${state.members.length} / --`} /><Stat label="LEVEL" value="--" /><Stat label="GLOBAL RANK" value="--" /></div></section>; }
function Stat({ label, value }: { label: string; value: string }) { return <div><small>{label}</small><strong>{value}</strong></div>; }
function GuildEmptyState({ onCreate, onFind }: { onCreate: () => void; onFind: () => void }) { return <section className="guild-empty-state"><div className="empty-emblem">♜</div><span className="eyebrow">NO GUILD MEMBERSHIP</span><h2>JOIN THE COMMUNITY</h2><p>Find a Guild or create your own base for the arena.</p><div className="guild-empty-actions"><button onClick={onFind}>FIND GUILD <small>{isGuildApiConfigured() ? 'SEARCH CATALOG' : 'API REQUIRED'}</small></button><button onClick={onCreate}>CREATE GUILD <span>↗</span></button></div><small className="guild-data-note">Guild search uses the connected Guild catalog and never invents results locally.</small></section>; }
function GuildTabContent({ tab, state, username, onLeave, onNotice }: { tab: GuildTab; state: GuildState; username: string; onLeave: () => void; onNotice: (notice: string) => void }) { if (tab === 'MEMBERS') return <Members state={state} />; if (tab === 'CHAT') return <GuildChat username={username} />; if (tab === 'RANKING') return <Unavailable title="GUILD RANKING" description="Ranking data requires a connected Guild leaderboard." />; if (tab === 'ACTIVITY') return <Activity state={state} />; if (tab === 'EVENTS') return <Unavailable title="GUILD EVENTS" description="Guild Events are coming soon. No event is active." />; if (tab === 'MANAGEMENT') return <Management state={state} username={username} onLeave={onLeave} onNotice={onNotice} />; return <Overview state={state} />; }
function Overview({ state }: { state: GuildState }) { return <><PanelHeading eyebrow="GUILD BASE" title="OVERVIEW" description="A clear view of your Guild's current state." /><div className="guild-overview-grid"><div className="guild-metric-panel"><span className="eyebrow">GUILD PROGRESS</span><h3>LEVEL --</h3><div className="empty-progress">GUILD XP DATA REQUIRED</div><p>Progression will appear after the Guild service is connected.</p></div><div className="guild-metric-panel"><span className="eyebrow">GUILD AURA</span><h3>--</h3><p>Aura totals are supplied by the server and never fabricated on the client.</p></div></div><div className="guild-feed-panel"><PanelHeading eyebrow="LATEST" title="ANNOUNCEMENT & ACTIVITY" description="No activity is generated locally." /><Activity state={state} /></div></>; }
function Members({ state }: { state: GuildState }) { return <><PanelHeading eyebrow="ROSTER" title={`MEMBERS · ${state.members.length} / --`} description="Only members returned by the Guild service are shown." /><div className="member-list">{state.members.map((member) => <div className="member-row" key={member.userId}><span className="member-avatar">{member.username.slice(0, 1).toUpperCase()}</span><div><strong>{member.username}</strong><small>ROLE: {member.role} · LEVEL -- · RANK --</small></div><span className="member-status">LOCAL OWNER</span></div>)}</div></>; }
function GuildChat({ username }: { username: string }) { const [messages, setMessages] = useState<ChatMessage[]>(() => getMessages('GUILD')); const [draft, setDraft] = useState(''); const [notice, setNotice] = useState(''); const endRef = useRef<HTMLDivElement>(null); const lastSent = useRef(0); useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]); function send(event: FormEvent) { event.preventDefault(); const content = draft.trim(); if (!content) return; if (Date.now() - lastSent.current < 1200) { setNotice('Please wait before sending another message.'); return; } lastSent.current = Date.now(); addMessage('GUILD', username, content); setMessages(getMessages('GUILD')); setDraft(''); setNotice(''); } return <section className="guild-chat-panel"><PanelHeading eyebrow="LOCAL CHANNEL" title="GUILD CHAT" description="Messages are stored locally until realtime transport is connected." /><div className="guild-message-list">{messages.length ? messages.map((message) => <GuildBubble key={message.id} message={message} onReact={(reaction) => { reactToMessage(message.id, reaction); setMessages(getMessages('GUILD')); }} />) : <div className="chat-empty"><span>◌</span><strong>NO MESSAGES YET</strong><small>Start the conversation with your Guild.</small></div>}<div ref={endRef} /></div><form className="guild-chat-input" onSubmit={send}><input value={draft} maxLength={80} onChange={(event) => setDraft(event.target.value)} placeholder="Message..." aria-label="Guild message" /><button type="submit" aria-label="Send Guild message">↗</button></form><small className="chat-note">{notice || '80 character limit · 1.2s cooldown · local chat mode'}</small></section>; }
function GuildBubble({ message, onReact }: { message: ChatMessage; onReact: (reaction: string) => void }) { return <div className="guild-bubble"><span className="chat-avatar">{message.username.slice(0, 1).toUpperCase()}</span><div><p><strong>{message.username}</strong><time>{new Date(message.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></p><span>{message.content}</span><div className="chat-reactions"><button onClick={() => onReact('🔥')}>🔥 {message.reactions['🔥'] || 0}</button><button onClick={() => onReact('😂')}>😂 {message.reactions['😂'] || 0}</button></div></div></div>; }
function Activity({ state }: { state: GuildState }) { return <div className="activity-list">{state.activity.length ? state.activity.map((activity) => <div className="activity-row" key={activity.id}><span>•</span><div><strong>{activity.text}</strong><small>{new Date(activity.createdAt).toLocaleString()}</small></div></div>) : <div className="guild-empty-inline">No guild activity yet.</div>}</div>; }
function Management({ state, username, onLeave, onNotice }: { state: GuildState; username: string; onLeave: () => void; onNotice: (notice: string) => void }) { const canManage = state.guild.ownerId === username; return <><PanelHeading eyebrow="AUTHORIZED ACTIONS" title="MANAGEMENT" description={canManage ? 'Owner controls are ready for server authorization.' : 'Management actions are restricted by the server role.'} /><div className="management-grid"><div><span className="eyebrow">GENERAL</span><InfoLine label="Guild Name" value={state.guild.name} /><InfoLine label="Privacy" value={state.guild.privacy} /><InfoLine label="Emblem" value={state.guild.emblem} /></div><div><span className="eyebrow">BACKEND ACTIONS</span><button disabled={!canManage} onClick={() => onNotice('Announcement API required.')}>CREATE ANNOUNCEMENT</button><button disabled={!canManage} onClick={() => onNotice('Member management API required.')}>MANAGE MEMBERS</button>{canManage ? <><button onClick={() => onNotice('Transfer ownership API required.')}>TRANSFER OWNERSHIP</button><button className="danger-link" onClick={() => onNotice('Delete Guild API required.')}>DELETE GUILD</button></> : <button className="danger-link" onClick={onLeave}>LEAVE GUILD</button>}</div></div></>; }
function InfoLine({ label, value }: { label: string; value: string }) { return <div className="info-line"><span>{label}</span><strong>{value}</strong></div>; }
function Unavailable({ title, description }: { title: string; description: string }) { return <section className="guild-unavailable"><span className="empty-emblem">◇</span><span className="eyebrow">COMING SOON</span><h2>{title}</h2><p>{description}</p></section>; }
function PanelHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="guild-panel-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div><span>✦</span></div>; }
function CreateGuildModal({ username, onClose, onCreated }: { username: string; onClose: () => void; onCreated: (state: GuildState) => void }) { const [name, setName] = useState(''); const [tag, setTag] = useState(''); const [description, setDescription] = useState(''); const [privacy, setPrivacy] = useState<GuildPrivacy>('PUBLIC'); const [error, setError] = useState(''); function submit(event: FormEvent) { event.preventDefault(); if (name.trim().length < 3 || name.trim().length > 24) return setError('Guild name must be 3-24 characters.'); if (!/^[a-z0-9]{2,5}$/i.test(tag)) return setError('Guild tag must be 2-5 letters or numbers.'); onCreated(createGuild({ name, tag, description, privacy, ownerId: username, username })); } return <div className="modal-backdrop"><form className="guild-create-modal" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose} aria-label="Close create guild">×</button><span className="eyebrow">COMMUNITY SETUP</span><h2>CREATE GUILD</h2><p>Guild creation is stored locally until the Guild API is connected.</p><label>GUILD NAME<input value={name} onChange={(event) => setName(event.target.value)} maxLength={24} placeholder="Your Guild name" /></label><label>GUILD TAG<input value={tag} onChange={(event) => setTag(event.target.value)} maxLength={5} placeholder="AURA" /></label><label>DESCRIPTION<textarea value={description} onChange={(event) => setDescription(event.target.value)} maxLength={120} placeholder="What does your community stand for?" /></label><label>PRIVACY<select value={privacy} onChange={(event) => setPrivacy(event.target.value as GuildPrivacy)}><option>PUBLIC</option><option>INVITE ONLY</option><option>PRIVATE</option></select></label>{error && <small className="form-error">{error}</small>}<div className="modal-actions"><button type="button" onClick={onClose}>CANCEL</button><button type="submit">CREATE GUILD</button></div></form></div>; }

function GuildSearchModal({ onClose }: { onClose: () => void }) { const [query, setQuery] = useState(''); const [results, setResults] = useState<GuildSearchResult[]>([]); const [status, setStatus] = useState<'idle' | 'loading' | 'empty' | 'error'>('idle'); async function search() { if (!isGuildApiConfigured()) { setStatus('error'); return; } setStatus('loading'); try { const next = await searchGuilds(query); setResults(next); setStatus(next.length ? 'idle' : 'empty'); } catch { setStatus('error'); } } function submit(event: FormEvent) { event.preventDefault(); void search(); } return <div className="modal-backdrop"><section className="guild-create-modal guild-search-modal"><button className="modal-close" onClick={onClose} aria-label="Close find Guild">×</button><span className="eyebrow">GUILD DIRECTORY</span><h2>FIND GUILD</h2><p>Search the live Guild catalog by name or tag.</p><form className="guild-search-form" onSubmit={submit}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Guild name or tag" aria-label="Search Guild" /><button type="submit" disabled={status === 'loading'}>{status === 'loading' ? 'SEARCHING...' : 'SEARCH'}</button></form>{status === 'error' && <div className="guild-search-state"><strong>{isGuildApiConfigured() ? 'UNABLE TO LOAD GUILDS' : 'GUILD API NOT CONFIGURED'}</strong><small>{isGuildApiConfigured() ? 'Check the service and retry.' : 'Set VITE_GUILD_API_URL to enable live Guild discovery.'}</small><button onClick={() => void search()}>RETRY</button></div>}{status === 'empty' && <div className="guild-search-state"><strong>NO GUILDS FOUND</strong><small>Try another name or tag.</small></div>}{status === 'idle' && results.length > 0 && <div className="guild-results">{results.map((guild) => <div className="guild-result" key={guild.id}><span className="member-avatar">{guild.name.slice(0, 1)}</span><div><strong>{guild.name} [{guild.tag}]</strong><small>{guild.privacy} · {guild.memberCount ?? '--'} / {guild.maxMembers ?? '--'} MEMBERS</small></div><button disabled title={guild.privacy === 'PUBLIC' ? 'Join requires the Guild membership API.' : 'This Guild does not accept direct joins.'}>{guild.privacy === 'PUBLIC' ? 'JOIN' : 'REQUEST'}</button></div>)}</div>}{!results.length && status === 'idle' && <div className="guild-search-state"><strong>SEARCH THE DIRECTORY</strong><small>Results will come from the Guild API.</small></div>}</section></div>; }